#include <assert.h>
#include <stdio.h>
#include <string.h>
#include "../src/marching.h"
#define WIDTH (30)
#define HEIGHT (30)
#define THRESHOLD (200)

/**
* Return an array generated by rand number
*/
uint8_t *makeImage(int width, int height)
{
    uint8_t *img = malloc(sizeof(uint8_t) * height * width);
    for (int i = 0; i < height; i++)
    {
        for (int j = 0; j < width; j++)
        {
            img[i * width + j] = rand() % 255;
        }
    }
    return img;
}

/** 
* Print the array
*/
void print_img(uint8_t *img, int width, int height)
{
    for (int i = 0; i < height; i++)
    {
        for (int j = 0; j < width; j++)
        {
            if (img[i * width + j] == 1)
            {
                printf("# ");
            }
            else if (img[i * width + j] == 0)
            {
                printf("  ");
            }
            else
            {
                printf("0 ");
            }
        }
        puts("");
    }
}

/** 
* test the bit image only contain 1 and 0
*/
int test_msquare_1bit_only_one_and_zero()
{

    uint8_t *img = makeImage(WIDTH, HEIGHT);
    uint8_t *data = msquare_1bit(img, WIDTH, HEIGHT, THRESHOLD);
    for (size_t i = 0; i < HEIGHT * WIDTH; i++)
    {
        assert((data[i] == 0) || (data[i] == 1));
    }
    free(data);
    free(img);
}

/**
 * test msquare_1bit
 * test the image that if pixel value>threshold, pixel = 1
 *                     if pixel value<threshold, pixel = 0
*/
int test_msquare_1bit_threshold()
{
    uint8_t *img = makeImage(WIDTH, HEIGHT);
    uint8_t *data = msquare_1bit(img, WIDTH, HEIGHT, THRESHOLD);
    for (size_t i = 0; i < HEIGHT * WIDTH; i++)
    {
        if (img[i] > THRESHOLD)
        {
            assert(data[i] == 1);
        }
        else
        {
            assert(data[i] == 0);
        }
    }

    free(data);
    free(img);
}

/**
 * test msquare_detect
 * test all segment value <16 and is positive
*/
int test_msquare_detect1()
{
    uint8_t *img = makeImage(WIDTH, HEIGHT);
    uint8_t *data = msquare_1bit(img, WIDTH, HEIGHT, THRESHOLD);

    //initial segments and set all value as 0
    size_t segment_len = WIDTH * HEIGHT / 9;
    uint8_t *segments = (uint8_t *)malloc(sizeof(uint8_t) * segment_len);
    memset(segments, 0, segment_len);

    // print_img(data, WIDTH, HEIGHT);
    msquare_detect(data, WIDTH, HEIGHT, segments, segment_len);
    for (size_t i = 0; i < segment_len; i++)
    {
        assert(segments[i] < 16);
        assert(segments[i] >= 0);
    }
    free(img);
    free(data);
}

/**
 * Test msquare_fill
 * Chcek the output manully
*/
int test_msquare_fill1()
{
    uint8_t *img = makeImage(WIDTH, HEIGHT);
    uint8_t *data = msquare_1bit(img, WIDTH, HEIGHT, THRESHOLD);

    //initial segments and set all value as 0
    size_t segment_len = WIDTH * HEIGHT / 9;
    uint8_t *segments = (uint8_t *)malloc(sizeof(uint8_t) * segment_len);
    memset(segments, 0, segment_len);

    msquare_detect(data, WIDTH, HEIGHT, segments, segment_len);

    //print out before
    print_img(data, WIDTH, HEIGHT);
    puts(""); //separate two print result

    //deal with data, set the contour line as 2
    msquare_fill(data, WIDTH, HEIGHT, segments, segment_len, 2, 2);

    //print out after
    print_img(data, WIDTH, HEIGHT);
    free(img);
    free(data);
}

int main()
{
    test_msquare_1bit_only_one_and_zero();
    test_msquare_1bit_threshold();
    test_msquare_detect1();
    test_msquare_fill1();
}